const VITE_START_HOUR = window.VITE_START_HOUR ;
const VITE_NUMBER_OF_HOURS = window.VITE_ADDITIONAL_NEXT_DAY_HOURS ;
const VITE_API_DOMAIN = window.VITE_API_DOMAIN ;
const VITE_VAM_INTERVAL = window.VITE_VAM_INTERVAL ;
const VITE_CAM_INTERVAL = window.VITE_CAM_INTERVAL ;
const VITE_LIVE_SCROLLING_SPEED = window.VITE_LIVE_SCROLLING_SPEED ;

export {
  VITE_START_HOUR,
  VITE_NUMBER_OF_HOURS,
  VITE_API_DOMAIN,
  VITE_VAM_INTERVAL,
  VITE_CAM_INTERVAL,
  VITE_LIVE_SCROLLING_SPEED,
};
